//! ECS systems for game logic.

use hecs::{Entity, World};

use crate::combat::{
    entity_at, melee_attack, ranged_attack, remove_dead, BASE_RANGED_DAMAGE,
    RANGED_OPTIMAL_DISTANCE,
};
use crate::ecs::components::{AIType, Enemy, Position};
use crate::hex::{pathfind, Hex, HexGrid, Tile};

/// Messages generated by AI actions.
#[derive(Debug, Clone)]
pub struct AIMessage(pub String);

/// Run AI for all enemies.
pub fn run_enemy_ai<T: Tile>(
    world: &mut World,
    grid: &HexGrid<T>,
    player: Entity,
) -> Vec<AIMessage> {
    let mut messages = Vec::new();

    // Get player position
    let player_pos = match world.get::<&Position>(player) {
        Ok(p) => p.0,
        Err(_) => return messages,
    };

    // Collect enemies to process (can't iterate and mutate at same time)
    let enemies: Vec<(Entity, Hex, i32, AIType)> = world
        .query::<(&Position, &Enemy)>()
        .iter()
        .map(|(e, (pos, enemy))| (e, pos.0, enemy.aggro_range, enemy.ai_type))
        .collect();

    for (entity, enemy_pos, aggro_range, ai_type) in enemies {
        // Skip if too far away (not aggro'd)
        let dist = enemy_pos.distance(player_pos);
        if dist > aggro_range {
            continue;
        }

        match ai_type {
            AIType::Melee => {
                // If adjacent, attack
                if dist == 1 {
                    let result = melee_attack(world, entity, player, 8);
                    if let crate::combat::AttackResult::Hit { damage, killed: _ } = result {
                        messages.push(AIMessage(format!("Enemy hits you for {} damage!", damage)));
                    }
                } else {
                    // Try to move toward player
                    if let Some(path) = pathfind(grid, enemy_pos, player_pos) {
                        if path.len() > 1 {
                            let next_pos = path[1];
                            // Check if position is free
                            if entity_at(world, next_pos, entity).is_none() {
                                if let Ok(mut pos) = world.get::<&mut Position>(entity) {
                                    pos.0 = next_pos;
                                }
                            }
                        }
                    }
                }
            }
            AIType::Ranged => {
                // Ranged AI: maintain optimal distance and attack from afar
                let optimal_dist = RANGED_OPTIMAL_DISTANCE;
                let max_range = aggro_range;

                if dist <= max_range && dist >= 2 {
                    // In range and not too close - attack!
                    let result = ranged_attack(world, entity, player, BASE_RANGED_DAMAGE);
                    if let crate::combat::AttackResult::Hit { damage, killed: _ } = result {
                        messages.push(AIMessage(format!("Enemy casts a spell for {} damage!", damage)));
                    }
                }

                // Movement: try to maintain optimal distance
                if dist < optimal_dist - 1 {
                    // Too close - retreat
                    // Find hex that's further from player
                    let neighbors = enemy_pos.neighbors();
                    let mut best_pos = None;
                    let mut best_dist = dist;
                    for neighbor in neighbors {
                        if grid.get(neighbor).is_some_and(|t| t.is_walkable()) {
                            let new_dist = neighbor.distance(player_pos);
                            if new_dist > best_dist && entity_at(world, neighbor, entity).is_none() {
                                best_dist = new_dist;
                                best_pos = Some(neighbor);
                            }
                        }
                    }
                    if let Some(next_pos) = best_pos {
                        if let Ok(mut pos) = world.get::<&mut Position>(entity) {
                            pos.0 = next_pos;
                        }
                    }
                } else if dist > max_range {
                    // Too far - approach using pathfinding
                    if let Some(path) = pathfind(grid, enemy_pos, player_pos) {
                        if path.len() > 1 {
                            let next_pos = path[1];
                            if entity_at(world, next_pos, entity).is_none() {
                                if let Ok(mut pos) = world.get::<&mut Position>(entity) {
                                    pos.0 = next_pos;
                                }
                            }
                        }
                    }
                }
                // At optimal distance - stay put and attack
            }
            AIType::Patrol => {
                // Patrol AI: wander randomly until player is spotted, then chase
                let detection_range = aggro_range / 2; // Shorter detection range

                if dist <= detection_range {
                    // Spotted player! Chase like melee
                    if dist == 1 {
                        let result = melee_attack(world, entity, player, 8);
                        if let crate::combat::AttackResult::Hit { damage, killed: _ } = result {
                            messages.push(AIMessage(format!("Patroller attacks for {} damage!", damage)));
                        }
                    } else if let Some(path) = pathfind(grid, enemy_pos, player_pos) {
                        if path.len() > 1 {
                            let next_pos = path[1];
                            if entity_at(world, next_pos, entity).is_none() {
                                if let Ok(mut pos) = world.get::<&mut Position>(entity) {
                                    pos.0 = next_pos;
                                }
                            }
                        }
                    }
                } else {
                    // Wandering - pick a random walkable neighbor
                    let neighbors = enemy_pos.neighbors();
                    let walkable: Vec<Hex> = neighbors
                        .into_iter()
                        .filter(|h| {
                            grid.get(*h).is_some_and(|t| t.is_walkable())
                                && entity_at(world, *h, entity).is_none()
                        })
                        .collect();

                    if !walkable.is_empty() {
                        // Use position-based deterministic "random" for consistent behavior
                        let idx = ((enemy_pos.x.abs() + enemy_pos.y.abs()) as usize) % walkable.len();
                        let next_pos = walkable[idx];
                        if let Ok(mut pos) = world.get::<&mut Position>(entity) {
                            pos.0 = next_pos;
                        }
                    }
                }
            }
        }
    }

    // Remove dead entities
    remove_dead(world);

    messages
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ecs::components::{Health, Player};

    fn simple_grid() -> HexGrid<crate::dungeon::DungeonTile> {
        use crate::dungeon::DungeonTile;
        let mut grid = HexGrid::new();
        // Create a small floor area
        for q in -5..=5 {
            for r in -5..=5 {
                let s = -q - r;
                if std::panic::catch_unwind(|| Hex::new(q, r, s)).is_ok() {
                    grid.set(Hex::new(q, r, s), DungeonTile::Floor);
                }
            }
        }
        grid
    }

    #[test]
    fn test_enemy_approaches_player() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        let enemy_pos = Hex::new(3, 0, -3);
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Melee,
                aggro_range: 6,
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Enemy should have moved closer
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        assert!(new_pos.distance(Hex::origin()) < enemy_pos.distance(Hex::origin()));
    }

    #[test]
    fn test_enemy_attacks_adjacent() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        // Place enemy adjacent to player
        let enemy_pos = Hex::origin().neighbor(0);
        world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Melee,
                aggro_range: 6,
            },
        ));

        let messages = run_enemy_ai(&mut world, &grid, player);

        // Should have attacked and generated a message
        assert!(!messages.is_empty());
        // Player should have taken damage
        let health = world.get::<&Health>(player).unwrap();
        assert!(health.current < 100);
    }

    #[test]
    fn test_enemy_ignores_far_player() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        let enemy_pos = Hex::new(5, -2, -3); // Outside aggro range of 3
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Melee,
                aggro_range: 3, // Short aggro range
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Enemy should not have moved
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        assert_eq!(new_pos, enemy_pos);
    }

    #[test]
    fn test_ranged_enemy_maintains_distance() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        // Place ranged enemy close to player (should back away)
        let enemy_pos = Hex::new(2, 0, -2);
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Ranged,
                aggro_range: 8,
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Ranged enemy should maintain optimal distance (4 hexes)
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        let distance = new_pos.distance(Hex::origin());
        // Should be at or moving toward optimal range
        assert!(distance >= 2, "Ranged enemy should not get closer");
    }

    #[test]
    fn test_ranged_enemy_attacks_at_range() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        // Place ranged enemy at optimal distance
        let enemy_pos = Hex::new(4, 0, -4);
        world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Ranged,
                aggro_range: 8,
            },
        ));

        let messages = run_enemy_ai(&mut world, &grid, player);

        // Should have attacked from range
        assert!(!messages.is_empty(), "Ranged enemy should attack at optimal range");
        // Player should have taken damage
        let health = world.get::<&Health>(player).unwrap();
        assert!(health.current < 100, "Player should take ranged damage");
    }

    #[test]
    fn test_patrol_enemy_wanders() {
        let grid = simple_grid();
        let mut world = World::new();

        // Player far away (outside detection range)
        let player = world.spawn((Position(Hex::new(5, 0, -5)), Health::new(100), Player));

        // Place patrol enemy
        let enemy_pos = Hex::new(-3, 0, 3);
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Patrol,
                aggro_range: 6, // Detection is half of this (3)
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Patrol enemy should have wandered (moved to a neighbor)
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        // Should have moved to an adjacent hex or stayed (if no valid neighbors)
        let moved = new_pos != enemy_pos;
        let adjacent = enemy_pos.distance(new_pos) <= 1;
        assert!(moved || adjacent, "Patrol enemy should wander when player not spotted");
    }

    #[test]
    fn test_patrol_enemy_chases_when_spotted() {
        let grid = simple_grid();
        let mut world = World::new();

        // Player close enough to be detected (within half of aggro_range)
        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        // Place patrol enemy within detection range (aggro_range/2 = 3)
        let enemy_pos = Hex::new(2, 0, -2);
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Patrol,
                aggro_range: 6, // Detection range is 3
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Patrol enemy should have moved closer to player (chasing)
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        assert!(
            new_pos.distance(Hex::origin()) <= enemy_pos.distance(Hex::origin()),
            "Patrol enemy should chase when player spotted"
        );
    }
}
