//! ECS systems for game logic.

use hecs::{Entity, World};

use crate::combat::{entity_at, melee_attack, remove_dead};
use crate::ecs::components::{AIType, Enemy, Position};
use crate::hex::{pathfind, Hex, HexGrid, Tile};

/// Messages generated by AI actions.
#[derive(Debug, Clone)]
pub struct AIMessage(pub String);

/// Run AI for all enemies.
pub fn run_enemy_ai<T: Tile>(
    world: &mut World,
    grid: &HexGrid<T>,
    player: Entity,
) -> Vec<AIMessage> {
    let mut messages = Vec::new();

    // Get player position
    let player_pos = match world.get::<&Position>(player) {
        Ok(p) => p.0,
        Err(_) => return messages,
    };

    // Collect enemies to process (can't iterate and mutate at same time)
    let enemies: Vec<(Entity, Hex, i32, AIType)> = world
        .query::<(&Position, &Enemy)>()
        .iter()
        .map(|(e, (pos, enemy))| (e, pos.0, enemy.aggro_range, enemy.ai_type))
        .collect();

    for (entity, enemy_pos, aggro_range, ai_type) in enemies {
        // Skip if too far away (not aggro'd)
        let dist = enemy_pos.distance(player_pos);
        if dist > aggro_range {
            continue;
        }

        match ai_type {
            AIType::Melee => {
                // If adjacent, attack
                if dist == 1 {
                    let result = melee_attack(world, entity, player, 8);
                    if let crate::combat::AttackResult::Hit { damage, killed: _ } = result {
                        messages.push(AIMessage(format!("Enemy hits you for {} damage!", damage)));
                    }
                } else {
                    // Try to move toward player
                    if let Some(path) = pathfind(grid, enemy_pos, player_pos) {
                        if path.len() > 1 {
                            let next_pos = path[1];
                            // Check if position is free
                            if entity_at(world, next_pos, entity).is_none() {
                                if let Ok(mut pos) = world.get::<&mut Position>(entity) {
                                    pos.0 = next_pos;
                                }
                            }
                        }
                    }
                }
            }
            AIType::Ranged => {
                // TODO: Implement ranged AI (keep distance, cast spells)
            }
            AIType::Patrol => {
                // TODO: Implement patrol AI (wander until sees player)
            }
        }
    }

    // Remove dead entities
    remove_dead(world);

    messages
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ecs::components::{Health, Player};

    fn simple_grid() -> HexGrid<crate::dungeon::DungeonTile> {
        use crate::dungeon::DungeonTile;
        let mut grid = HexGrid::new();
        // Create a small floor area
        for q in -5..=5 {
            for r in -5..=5 {
                let s = -q - r;
                if let Ok(_) = std::panic::catch_unwind(|| Hex::new(q, r, s)) {
                    grid.set(Hex::new(q, r, s), DungeonTile::Floor);
                }
            }
        }
        grid
    }

    #[test]
    fn test_enemy_approaches_player() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        let enemy_pos = Hex::new(3, 0, -3);
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Melee,
                aggro_range: 6,
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Enemy should have moved closer
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        assert!(new_pos.distance(Hex::origin()) < enemy_pos.distance(Hex::origin()));
    }

    #[test]
    fn test_enemy_attacks_adjacent() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        // Place enemy adjacent to player
        let enemy_pos = Hex::origin().neighbor(0);
        world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Melee,
                aggro_range: 6,
            },
        ));

        let messages = run_enemy_ai(&mut world, &grid, player);

        // Should have attacked and generated a message
        assert!(!messages.is_empty());
        // Player should have taken damage
        let health = world.get::<&Health>(player).unwrap();
        assert!(health.current < 100);
    }

    #[test]
    fn test_enemy_ignores_far_player() {
        let grid = simple_grid();
        let mut world = World::new();

        let player = world.spawn((Position(Hex::origin()), Health::new(100), Player));

        let enemy_pos = Hex::new(5, -2, -3); // Outside aggro range of 3
        let enemy = world.spawn((
            Position(enemy_pos),
            Health::new(20),
            Enemy {
                ai_type: AIType::Melee,
                aggro_range: 3, // Short aggro range
            },
        ));

        run_enemy_ai(&mut world, &grid, player);

        // Enemy should not have moved
        let new_pos = world.get::<&Position>(enemy).unwrap().0;
        assert_eq!(new_pos, enemy_pos);
    }
}
